"use client";
import { useState, useEffect, useCallback, useRef } from "react";
export interface ChatNotification { id: string; chatId: string; emergencyId: string; senderId: string; senderName: string; content: string; timestamp: number; otherUserId: string; otherUserName: string; read: boolean; }
const eid = (v: unknown): string => { if (!v) return ""; if (typeof v === "string") return v; if (typeof v === "object" && v !== null && "$oid" in (v as any)) return String((v as any).$oid); return String(v); };
export function useChatNotifications({ userId, interval = 5000, enabled = true }: { userId: string | undefined; interval?: number; enabled?: boolean }) {
  const [notifications, setNotifications] = useState<ChatNotification[]>([]); const [unreadCount, setUnreadCount] = useState(0); const lastRef = useRef<Record<string, number>>({});
  const beep = useCallback(() => { try { const c = new (window.AudioContext || (window as any).webkitAudioContext)(); const o = c.createOscillator(); const g = c.createGain(); o.connect(g); g.connect(c.destination); o.frequency.value = 880; o.type = "sine"; g.gain.value = 0.15; o.start(); g.gain.exponentialRampToValueAtTime(0.001, c.currentTime + 0.3); o.stop(c.currentTime + 0.3); } catch {} }, []);
  const poll = useCallback(async () => { const uid = eid(userId); if (!uid) return; try { const r = await fetch(`/api/chat?userId=${encodeURIComponent(uid)}&type=emergency`); if (!r.ok) return; const chats = (await r.json()).chats || []; for (const ch of chats) { const cid = ch._id; if (!cid) continue; const mr = await fetch(`/api/chat/${cid}`); if (!mr.ok) continue; const msgs = (await mr.json()).messages || []; const prev = lastRef.current[cid] ?? -1; if (prev === -1) { lastRef.current[cid] = msgs.length; continue; } if (msgs.length > prev) { const others = msgs.slice(prev).filter((m: any) => eid(m.senderId) !== uid); const ps: string[] = ch.participants || []; const ns: string[] = ch.participantNames || []; const oi = ps.findIndex((p: string) => eid(p) !== uid); const ouid = oi >= 0 ? eid(ps[oi]) : ""; const oun = oi >= 0 ? (ns[oi] || "User") : "User"; for (const m of others) { const n: ChatNotification = { id: `${cid}-${Date.now()}-${Math.random()}`, chatId: cid, emergencyId: ch.emergencyId || "", senderId: eid(m.senderId), senderName: m.senderName || oun, content: m.content || "New message", timestamp: m.createdAt ? new Date(m.createdAt).getTime() : Date.now(), otherUserId: ouid, otherUserName: oun, read: false }; setNotifications((p) => { if (p.some((x) => x.chatId === cid && x.content === n.content && x.senderId === n.senderId && Math.abs(x.timestamp - n.timestamp) < 10000)) return p; return [...p.slice(-19), n]; }); setUnreadCount((c) => c + 1); } if (others.length > 0) beep(); } lastRef.current[cid] = msgs.length; } } catch {} }, [userId, beep]);
  useEffect(() => { if (!enabled || !userId) return; poll(); const t = setInterval(poll, interval); return () => clearInterval(t); }, [enabled, userId, interval, poll]);
  return { notifications, unreadCount, dismiss: useCallback((id: string) => setNotifications((p) => p.filter((n) => n.id !== id)), []), dismissAll: useCallback(() => { setNotifications([]); setUnreadCount(0); }, []), clearUnread: useCallback(() => { setUnreadCount(0); setNotifications((p) => p.map((n) => ({ ...n, read: true }))); }, []), markChatRead: useCallback((cid: string, count: number) => { lastRef.current[cid] = count; }, []) };
}