"use client";
import { useState } from "react";
import { useAppStore } from "@/lib/store";
import type { Specialist } from "@/types";
interface Props { specialist: Specialist; onBack: () => void; }
export default function DirectionsMap({ specialist, onBack }: Props) {
  const { currentLocation } = useAppStore(); const [mode, setMode] = useState<"driving"|"walking"|"transit">("driving");
  const origin = currentLocation ? `${currentLocation.lat},${currentLocation.lng}` : "52.5200,13.4050"; const dest = `${specialist.geometry.location.lat},${specialist.geometry.location.lng}`; const apiKey = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY;
  return (
    <div className="min-h-screen bg-[#f8fafc] text-[#1e293b]">
      <div className="bg-white/80 backdrop-blur-xl border-b border-[#e2e8f0] sticky top-0 z-50"><div className="max-w-6xl mx-auto px-4 py-3.5 flex items-center gap-4"><button onClick={onBack} className="p-2 hover:bg-[#f1f5f9] rounded-xl transition-colors"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg></button><div><h1 className="font-bold text-lg font-[Outfit]">Directions</h1><p className="text-[#475569] text-xs truncate max-w-[200px]">{specialist.name}</p></div></div></div>
      <div className="bg-white border-b border-[#e2e8f0] p-4"><div className="max-w-6xl mx-auto flex items-center gap-4"><div className="w-11 h-11 bg-[#3b82f6]/10 rounded-xl flex items-center justify-center"><svg className="w-5 h-5 text-[#3b82f6]" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg></div><div className="flex-1 min-w-0"><h3 className="font-bold truncate">{specialist.name}</h3><p className="text-[#475569] text-sm truncate">{specialist.vicinity}</p><p className="text-[#3b82f6] text-sm">{specialist.formatted_distance}</p></div><div className="flex gap-2">{specialist.formatted_phone_number && <button onClick={() => window.open(`tel:${specialist.formatted_phone_number}`, "_self")} className="bg-[#10b981]/10 text-[#10b981] px-4 py-2 rounded-xl text-sm font-medium">Call</button>}<button onClick={() => window.open(`https://www.google.com/maps/dir/?api=1&destination=${dest}`, "_blank")} className="bg-[#3b82f6] hover:bg-[#2563eb] text-white px-4 py-2 rounded-xl text-sm font-medium transition-colors">Open Maps</button></div></div></div>
      <div className="bg-white border-b border-[#e2e8f0] p-3"><div className="max-w-6xl mx-auto flex justify-center gap-2">{([["driving","Car","#3b82f6"],["walking","Walk","#10b981"],["transit","Transit","#8b5cf6"]] as const).map(([m,l,c]) => (<button key={m} onClick={() => setMode(m as any)} className={`px-5 py-2 rounded-xl text-sm font-medium transition-all ${mode === m ? "text-white shadow-md" : "bg-[#f1f5f9] text-[#475569] hover:text-[#1e293b]"}`} style={mode === m ? { background: c } : {}}>{l}</button>))}</div></div>
      <div className="flex-1 relative"><div className="absolute inset-0"><iframe key={mode} src={`https://www.google.com/maps/embed/v1/directions?key=${apiKey}&origin=${origin}&destination=${dest}&mode=${mode}`} width="100%" height="100%" style={{ border: 0, minHeight: "65vh" }} allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></div>
      <div className="bg-white border-t border-[#e2e8f0] p-4"><div className="max-w-6xl mx-auto flex justify-center"><button onClick={() => { if (currentLocation) window.open(`https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${dest}&travelmode=${mode}`, "_blank"); }} className="bg-[#3b82f6] hover:bg-[#2563eb] text-white font-medium py-3 px-8 rounded-xl transition-colors shadow-md shadow-[#3b82f6]/20">Start Navigation</button></div></div>
    </div>);
}