"use client";
import { useState } from "react";
import { useAppStore } from "@/lib/store";
import { useChatNotifications } from "@/lib/useChatNotifications";
import EmergencyChat from "@/components/ui/EmergencyChat";
import NotificationSidebar, { NotificationBell } from "@/components/ui/NotificationSidebar";
import type { EmergencyData } from "@/types";
interface Props { emergency: EmergencyData; onBack: () => void; onGetDirections: (e: EmergencyData) => void; }
export default function EmergencyResponse({ emergency, onBack, onGetDirections }: Props) {
  const { user } = useAppStore(); const [showChat, setShowChat] = useState(false); const [sidebar, setSidebar] = useState(false);
  const { notifications, unreadCount, dismissAll, clearUnread } = useChatNotifications({ userId: user?._id, enabled: !!user?._id, interval: 4000 });
  const phone = emergency.phoneNumber || emergency.reporterPhone;
  return (
    <div className="min-h-screen bg-[#f8fafc] text-[#1e293b] relative">
      <NotificationSidebar open={sidebar} onClose={() => setSidebar(false)} notifications={notifications} onNotificationClick={() => { setSidebar(false); clearUnread(); setShowChat(true); }} onClearAll={dismissAll} unreadCount={unreadCount} />
      <div className="bg-[#ef4444]/5 backdrop-blur-xl border-b border-[#ef4444]/20 sticky top-0 z-50"><div className="max-w-6xl mx-auto px-4 py-3.5 flex items-center justify-between"><div className="flex items-center gap-3"><button onClick={onBack} className="p-2 hover:bg-[#f1f5f9] rounded-xl"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg></button><div className="w-2.5 h-2.5 bg-[#ef4444] rounded-full animate-pulse" /><h1 className="font-bold text-lg font-[Outfit]">Emergency Response</h1></div><NotificationBell count={unreadCount} onClick={() => setSidebar(true)} /></div></div>
      <div className="max-w-6xl mx-auto px-4 py-6 space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <button onClick={() => phone ? window.open(`tel:${phone}`, "_self") : alert("No phone")} className="bg-[#10b981] hover:bg-[#059669] text-white py-4 px-5 rounded-2xl flex items-center justify-center gap-3 transition-colors shadow-md shadow-[#10b981]/10"><div><div className="font-bold font-[Outfit]">Call Patient</div><div className="text-sm opacity-80">{phone || "N/A"}</div></div></button>
          <button onClick={() => onGetDirections(emergency)} className="bg-[#3b82f6] hover:bg-[#2563eb] text-white py-4 px-5 rounded-2xl flex items-center justify-center gap-3 transition-colors shadow-md shadow-[#3b82f6]/10"><div><div className="font-bold font-[Outfit]">Get Directions</div><div className="text-sm opacity-80">Live Navigation</div></div></button>
          <button onClick={() => { if (!emergency.id || !emergency.patientId) { alert("Not available"); return; } clearUnread(); setShowChat(true); }} className={`bg-[#8b5cf6] hover:bg-[#7c3aed] text-white py-4 px-5 rounded-2xl flex items-center justify-center gap-3 transition-colors shadow-md shadow-[#8b5cf6]/10 relative ${unreadCount > 0 ? "ring-2 ring-[#8b5cf6]/30" : ""}`}><div><div className="font-bold font-[Outfit]">Chat</div><div className="text-sm opacity-80">{unreadCount > 0 ? `${unreadCount} new` : "Message Patient"}</div></div>{unreadCount > 0 && <span className="absolute -top-2 -right-2 w-6 h-6 bg-[#ef4444] text-white text-xs font-bold rounded-full flex items-center justify-center ring-2 ring-[#f8fafc]">{unreadCount}</span>}</button>
        </div>
        {showChat && emergency.id && emergency.patientId && <EmergencyChat emergencyId={emergency.id} otherUserId={emergency.patientId} otherUserName={emergency.patientName || "Patient"} onClose={() => setShowChat(false)} title="Chat with Patient" />}
        <div className="bg-white rounded-2xl border border-[#e2e8f0] p-6 shadow-sm"><h2 className="text-lg font-bold text-[#ef4444] font-[Outfit] mb-4">Patient Information</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div className="space-y-3"><div className="flex items-center gap-3"><div className="w-12 h-12 bg-[#3b82f6]/10 rounded-xl flex items-center justify-center"><span className="text-[#3b82f6] font-bold text-lg">{emergency.patientName?.charAt(0)?.toUpperCase() || "P"}</span></div><div><h3 className="font-bold font-[Outfit]">{emergency.patientName || "Patient"}</h3><p className="text-[#94a3b8] text-sm">Emergency Contact</p></div></div><p className="text-[#475569] text-sm">Age: {emergency.age || "N/A"}</p><p className="text-[#475569] text-sm">Phone: {phone || "N/A"}</p></div>
            <div className="space-y-3"><h4 className="font-semibold text-[#f59e0b]">Medical Info</h4><div className="bg-[#f8fafc] p-3 rounded-xl border border-[#e2e8f0]"><span className="text-[#ef4444] text-xs font-medium">Blood</span><p className="text-[#1e293b] font-bold">{emergency.bloodGroup || "Unknown"}</p></div><div className="bg-[#f8fafc] p-3 rounded-xl border border-[#e2e8f0]"><span className="text-[#f59e0b] text-xs font-medium">Allergies</span><p className="text-[#1e293b] text-sm">{emergency.allergies?.length ? emergency.allergies.join(", ") : "None"}</p></div><div className="bg-[#f8fafc] p-3 rounded-xl border border-[#e2e8f0]"><span className="text-[#3b82f6] text-xs font-medium">Conditions</span><p className="text-[#1e293b] text-sm">{emergency.medicalConditions?.length ? emergency.medicalConditions.join(", ") : "None"}</p></div></div></div>
          {emergency.description && <div className="mt-5 bg-[#ef4444]/5 border border-[#ef4444]/20 p-4 rounded-xl"><h4 className="text-[#ef4444] font-semibold text-sm mb-1">Description</h4><p className="text-[#1e293b] text-sm">{emergency.description}</p></div>}
        </div>
        <div className="bg-white rounded-2xl border border-[#e2e8f0] p-6 shadow-sm"><h2 className="text-lg font-bold text-[#3b82f6] font-[Outfit] mb-4">Actions</h2><div className="grid grid-cols-2 gap-3"><button onClick={() => alert("En route")} className="bg-[#f59e0b]/10 text-[#f59e0b] py-3 rounded-xl text-sm font-medium hover:bg-[#f59e0b]/20 transition-colors">⚡ En Route</button><button onClick={() => alert("Arrived")} className="bg-[#10b981]/10 text-[#10b981] py-3 rounded-xl text-sm font-medium hover:bg-[#10b981]/20 transition-colors">✅ Arrived</button><button onClick={() => { if (confirm("Mark resolved?")) { onBack(); } }} className="bg-[#3b82f6]/10 text-[#3b82f6] py-3 rounded-xl text-sm font-medium hover:bg-[#3b82f6]/20 transition-colors">✅ Resolved</button><button onClick={() => window.open("tel:911", "_self")} className="bg-[#ef4444]/10 text-[#ef4444] py-3 rounded-xl text-sm font-medium hover:bg-[#ef4444]/20 transition-colors">🚨 Call 911</button></div></div>
      </div>
    </div>);
}