"use client";
import { useState, useEffect } from "react";
import { useAppStore } from "@/lib/store";
import { enrichWithDistance } from "@/lib/helpers";
import type { Specialist } from "@/types";
interface Props { onBack: () => void; onGetDirections: (p: Specialist) => void; }
export default function PharmacySearch({ onBack, onGetDirections }: Props) {
  const { currentLocation } = useAppStore(); const [results, setResults] = useState<Specialist[]>([]); const [loading, setLoading] = useState(false); const [query, setQuery] = useState(""); const [error, setError] = useState("");
  const search = async () => { if (!currentLocation) { setError("Location required"); return; } setLoading(true); setError(""); try { const r = await fetch("/api/places/search", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ location: currentLocation, query: query || "pharmacy", type: "pharmacy", radius: 10000 }) }); if (!r.ok) throw 0; setResults(enrichWithDistance((await r.json()).results, currentLocation.lat, currentLocation.lng) as Specialist[]); } catch { setError("Search failed."); } finally { setLoading(false); } };
  useEffect(() => { if (currentLocation) search(); }, [currentLocation]);
  return (
    <div className="min-h-screen bg-[#f8fafc] text-[#1e293b]">
      <div className="bg-white/80 backdrop-blur-xl border-b border-[#e2e8f0] sticky top-0 z-50"><div className="max-w-6xl mx-auto px-4 py-3.5 flex items-center gap-4"><button onClick={onBack} className="p-2 hover:bg-[#f1f5f9] rounded-xl transition-colors"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg></button><div><h1 className="font-bold text-lg font-[Outfit]">Find Pharmacies</h1><p className="text-[#475569] text-xs">Nearby pharmacies & stores</p></div></div></div>
      <div className="max-w-6xl mx-auto px-4 py-6">
        <div className="bg-white rounded-2xl p-5 mb-6 border border-[#e2e8f0] shadow-sm flex gap-3"><input type="text" placeholder="Search by name…" value={query} onChange={(e) => setQuery(e.target.value)} onKeyPress={(e) => e.key === "Enter" && search()} className="flex-1 bg-[#f1f5f9] border border-[#e2e8f0] rounded-xl px-4 py-3 text-[#1e293b] placeholder:text-[#94a3b8] focus:outline-none focus:border-[#10b981] transition-colors" /><button onClick={search} disabled={loading} className="bg-[#10b981] hover:bg-[#059669] disabled:opacity-50 text-white font-medium py-3 px-6 rounded-xl transition-colors text-sm">{loading ? "…" : "Search"}</button></div>
        {error && <div className="bg-[#ef4444]/10 border border-[#ef4444]/30 rounded-xl px-4 py-3 mb-6 text-[#ef4444] text-sm">{error}</div>}
        {results.length > 0 && <div><p className="text-[#475569] text-sm mb-4">{results.length} pharmacies</p><div className="grid gap-3">{results.map((p) => (<div key={p.place_id} className="bg-white rounded-xl border border-[#e2e8f0] p-5 hover:border-[#10b981]/40 hover:shadow-md transition-all"><div className="flex items-center gap-2 mb-2"><h3 className="font-bold">{p.name}</h3><span className="px-2 py-0.5 bg-[#10b981]/10 text-[#10b981] text-xs rounded-full">Pharmacy</span></div><div className="flex items-center gap-4 text-sm text-[#475569] mb-3"><span>{p.vicinity}</span><span className="text-[#10b981] font-medium">{p.formatted_distance}</span>{p.opening_hours && <span className={p.opening_hours.open_now ? "text-[#10b981]" : "text-[#ef4444]"}>{p.opening_hours.open_now ? "Open" : "Closed"}</span>}</div>{p.rating && <div className="flex items-center gap-2 mb-3 text-sm"><span className="text-[#f59e0b]">★</span><span>{p.rating}</span><span className="text-[#94a3b8]">({p.user_ratings_total})</span></div>}<div className="flex gap-2"><button onClick={() => onGetDirections(p)} className="flex-1 bg-[#10b981] hover:bg-[#059669] text-white py-2.5 rounded-xl text-sm font-medium transition-colors">Directions</button>{p.formatted_phone_number && <button onClick={() => window.open(`tel:${p.formatted_phone_number}`, "_self")} className="bg-[#3b82f6]/10 text-[#3b82f6] px-5 py-2.5 rounded-xl text-sm font-medium hover:bg-[#3b82f6]/20 transition-colors">Call</button>}</div></div>))}</div></div>}
        {!loading && results.length === 0 && !error && <p className="text-[#94a3b8] text-center py-12">No pharmacies found</p>}
      </div>
    </div>);
}