"use client";
import { useState, useEffect } from "react";
import { useAppStore } from "@/lib/store";
export default function ProfileScreen({ onBack, onLogout }: { onBack: () => void; onLogout: () => void }) {
  const { user, setUser } = useAppStore(); const [saving, setSaving] = useState(false); const [msg, setMsg] = useState(""); const [f, setF] = useState({ name: "", phone: "", bloodGroup: "", allergies: "", specialization: "", hospital: "", experience: "" }); const isDoc = user?.role === "doctor";
  useEffect(() => { if (!user) return; setF({ name: user.name || "", phone: user.phone || "", bloodGroup: (user as any).bloodGroup || "", allergies: ((user as any).allergies || []).join(", "), specialization: (user as any).specialization || "", hospital: (user as any).hospital || "", experience: (user as any).experience ? String((user as any).experience) : "" }); }, [user]);
  const save = async () => { if (!user?._id) return; setSaving(true); setMsg(""); try { const p: any = { userId: user._id, name: f.name, phone: f.phone }; if (isDoc) { p.specialization = f.specialization; p.hospital = f.hospital; p.experience = f.experience ? Number(f.experience) : undefined; } else { p.bloodGroup = f.bloodGroup; p.allergies = f.allergies.split(",").map((a) => a.trim()).filter(Boolean); } const r = await fetch("/api/users", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(p) }); const d = await r.json(); if (!r.ok) { setMsg(d.error || "Failed"); return; } if (d.user) setUser(d.user); setMsg("Profile updated successfully"); } catch { setMsg("Failed to update"); } finally { setSaving(false); } };
  if (!user) return null; const accent = isDoc ? "#10b981" : "#3b82f6";
  const Inp = ({ label, value, onChange, type = "text" }: any) => <div><label className="block text-sm text-[#475569] mb-2">{label}</label><input type={type} value={value} onChange={(e: any) => onChange(e.target.value)} className="w-full bg-[#f1f5f9] border border-[#e2e8f0] rounded-xl px-4 py-3 text-[#1e293b] focus:outline-none focus:border-[#3b82f6] transition-colors" /></div>;
  return (
    <div className="min-h-screen bg-[#f8fafc] text-[#1e293b]">
      <div className="bg-white border-b border-[#e2e8f0] sticky top-0 z-50"><div className="max-w-3xl mx-auto px-4 py-4 flex items-center gap-3"><button onClick={onBack} className="p-2 hover:bg-[#f1f5f9] rounded-xl transition-colors"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg></button><h1 className="font-bold text-xl font-[Outfit]">Profile Settings</h1></div></div>
      <div className="max-w-3xl mx-auto px-4 py-8">
        <div className="flex flex-col items-center mb-8"><div className="w-20 h-20 rounded-2xl flex items-center justify-center mb-3" style={{ background: `${accent}20` }}><span className="font-bold text-2xl" style={{ color: accent }}>{user.name?.charAt(0)?.toUpperCase()}</span></div><h2 className="text-xl font-bold font-[Outfit]">{user.name}</h2><p className="text-[#475569] text-sm">{user.email}</p><span className="mt-2 px-3 py-1 rounded-full text-xs font-medium" style={{ background: `${accent}15`, color: accent }}>{isDoc ? "Doctor" : "Patient"}</span></div>
        <div className="bg-white rounded-2xl p-6 border border-[#e2e8f0] shadow-sm space-y-5">
          <Inp label="Full Name" value={f.name} onChange={(v: string) => setF((p) => ({ ...p, name: v }))} />
          <Inp label="Phone Number" value={f.phone} onChange={(v: string) => setF((p) => ({ ...p, phone: v }))} />
          {isDoc ? <><Inp label="Specialization" value={f.specialization} onChange={(v: string) => setF((p) => ({ ...p, specialization: v }))} /><Inp label="Hospital" value={f.hospital} onChange={(v: string) => setF((p) => ({ ...p, hospital: v }))} /><Inp label="Experience (years)" value={f.experience} onChange={(v: string) => setF((p) => ({ ...p, experience: v }))} type="number" /></> : <><Inp label="Blood Group" value={f.bloodGroup} onChange={(v: string) => setF((p) => ({ ...p, bloodGroup: v }))} /><Inp label="Allergies (comma separated)" value={f.allergies} onChange={(v: string) => setF((p) => ({ ...p, allergies: v }))} /></>}
          {msg && <div className={`text-sm rounded-xl px-4 py-3 border ${msg.includes("success") ? "text-[#10b981] bg-[#10b981]/10 border-[#10b981]/30" : "text-[#ef4444] bg-[#ef4444]/10 border-[#ef4444]/30"}`}>{msg}</div>}
          <button onClick={save} disabled={saving} className="w-full text-white font-medium py-3.5 rounded-xl transition-colors disabled:opacity-60" style={{ background: accent }}>{saving ? "Saving…" : "Save Profile"}</button>
        </div>
        <div className="mt-8 bg-white rounded-2xl p-6 border border-[#e2e8f0] shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[#1e293b] font-medium">Sign Out</p><p className="text-[#94a3b8] text-sm">Log out of your account</p></div><button onClick={onLogout} className="bg-[#ef4444]/10 hover:bg-[#ef4444]/20 border border-[#ef4444]/30 text-[#ef4444] font-medium px-6 py-3 rounded-xl transition-colors flex items-center gap-2"><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" /></svg>Logout</button></div></div>
      </div>
    </div>);
}