"use client";
import { useState, useEffect } from "react";
import { useAppStore } from "@/lib/store";
import { enrichWithDistance, getSpecialistCategory } from "@/lib/helpers";
import type { Specialist } from "@/types";
const TYPES = [{ v: "doctor", l: "All Doctors", k: "doctor physician" },{ v: "cardiologist", l: "Cardiologist", k: "cardiologist heart" },{ v: "dermatologist", l: "Dermatologist", k: "dermatologist skin" },{ v: "pediatrician", l: "Pediatrician", k: "pediatrician children" },{ v: "gynecologist", l: "Gynecologist", k: "gynecologist women" },{ v: "orthopedic", l: "Orthopedic", k: "orthopedic bone" },{ v: "neurologist", l: "Neurologist", k: "neurologist brain" },{ v: "psychiatrist", l: "Psychiatrist", k: "psychiatrist mental" },{ v: "dentist", l: "Dentist", k: "dentist dental" },{ v: "hospital", l: "Hospital", k: "hospital medical center" }];
interface Props { onBack: () => void; onGetDirections: (s: Specialist) => void; }
export default function SpecialistSearch({ onBack, onGetDirections }: Props) {
  const { currentLocation } = useAppStore(); const [results, setResults] = useState<Specialist[]>([]); const [loading, setLoading] = useState(false); const [query, setQuery] = useState(""); const [type, setType] = useState("doctor"); const [error, setError] = useState("");
  const search = async () => { if (!currentLocation) { setError("Location required"); return; } setLoading(true); setError(""); try { const r = await fetch("/api/places/search", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ location: currentLocation, query: query || TYPES.find((t) => t.v === type)?.k || "doctor", type, radius: 10000 }) }); if (!r.ok) throw 0; setResults(enrichWithDistance((await r.json()).results, currentLocation.lat, currentLocation.lng) as Specialist[]); } catch { setError("Search failed."); } finally { setLoading(false); } };
  useEffect(() => { if (currentLocation) search(); }, [type, currentLocation]);
  return (
    <div className="min-h-screen bg-[#f8fafc] text-[#1e293b]">
      <div className="bg-white/80 backdrop-blur-xl border-b border-[#e2e8f0] sticky top-0 z-50"><div className="max-w-6xl mx-auto px-4 py-3.5 flex items-center gap-4"><button onClick={onBack} className="p-2 hover:bg-[#f1f5f9] rounded-xl transition-colors"><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg></button><div><h1 className="font-bold text-lg font-[Outfit]">Find Specialists</h1><p className="text-[#475569] text-xs">Nearby medical professionals</p></div></div></div>
      <div className="max-w-6xl mx-auto px-4 py-6">
        <div className="bg-white rounded-2xl p-5 mb-6 border border-[#e2e8f0] shadow-sm"><div className="grid md:grid-cols-2 gap-3 mb-3"><input type="text" placeholder="Search by name, specialty…" value={query} onChange={(e) => setQuery(e.target.value)} onKeyPress={(e) => e.key === "Enter" && search()} className="w-full bg-[#f1f5f9] border border-[#e2e8f0] rounded-xl px-4 py-3 text-[#1e293b] placeholder:text-[#94a3b8] focus:outline-none focus:border-[#3b82f6] transition-colors" /><select value={type} onChange={(e) => setType(e.target.value)} className="w-full bg-[#f1f5f9] border border-[#e2e8f0] rounded-xl px-4 py-3 text-[#1e293b] focus:outline-none focus:border-[#3b82f6]">{TYPES.map((t) => <option key={t.v} value={t.v}>{t.l}</option>)}</select></div><button onClick={search} disabled={loading} className="bg-[#3b82f6] hover:bg-[#2563eb] disabled:opacity-50 text-white font-medium py-3 px-6 rounded-xl transition-colors text-sm">{loading ? "Searching…" : "Search"}</button></div>
        {error && <div className="bg-[#ef4444]/10 border border-[#ef4444]/30 rounded-xl px-4 py-3 mb-6 text-[#ef4444] text-sm">{error}</div>}
        {results.length > 0 && <div><p className="text-[#475569] text-sm mb-4">{results.length} results</p><div className="grid gap-3">{results.map((s) => (<div key={s.place_id} className="bg-white rounded-xl border border-[#e2e8f0] p-5 hover:border-[#3b82f6]/40 hover:shadow-md transition-all"><div className="flex items-center gap-2 mb-2"><h3 className="font-bold">{s.name}</h3><span className="px-2 py-0.5 bg-[#3b82f6]/10 text-[#3b82f6] text-xs rounded-full">{getSpecialistCategory(s.types)}</span></div><div className="flex items-center gap-4 text-sm text-[#475569] mb-3"><span>{s.vicinity}</span><span className="text-[#3b82f6] font-medium">{s.formatted_distance}</span>{s.opening_hours && <span className={s.opening_hours.open_now ? "text-[#10b981]" : "text-[#ef4444]"}>{s.opening_hours.open_now ? "Open" : "Closed"}</span>}</div>{s.rating && <div className="flex items-center gap-2 mb-3 text-sm"><span className="text-[#f59e0b]">★</span><span>{s.rating}</span><span className="text-[#94a3b8]">({s.user_ratings_total})</span></div>}<div className="flex gap-2"><button onClick={() => onGetDirections(s)} className="flex-1 bg-[#3b82f6] hover:bg-[#2563eb] text-white py-2.5 rounded-xl text-sm font-medium transition-colors">Directions</button>{s.formatted_phone_number && <button onClick={() => window.open(`tel:${s.formatted_phone_number}`, "_self")} className="bg-[#10b981]/10 text-[#10b981] px-5 py-2.5 rounded-xl text-sm font-medium hover:bg-[#10b981]/20 transition-colors">Call</button>}</div></div>))}</div></div>}
        {!loading && results.length === 0 && !error && <p className="text-[#94a3b8] text-center py-12">No specialists found</p>}
      </div>
    </div>);
}